spring:
  flyway:
    cleanDisabled: false   # Разрешаем flyway.clean() — ТОЛЬКО для dev!
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/dev

  jpa:
    show-sql: true

logging:
  level:
    com.example.roombook: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG
