server:
  port: 8888

spring:
  application:
    name: BookingSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/roombook
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    flyway:
      enabled: true
      locations: classpath:db/migration
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hidden method:
      filter:
        enabled: true
  app:
    scheduling:
      expiredBookingsRate: 1m

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: debug
